.api_gateway_rules: &api_gateway_rules
  rules:
    - changes:
        - src/api-gateway/**/*
      when: always
    - when: never

build_api-gateway:
  stage: build
  <<: *api_gateway_rules
  script:
    - docker images "jubair2002/api-gateway*" -q | xargs -r docker rmi -f
    - docker build --no-cache -t jubair2002/api-gateway:api-gateway-$CI_COMMIT_SHORT_SHA src/api-gateway

push_api-gateway:
  stage: push
  <<: *api_gateway_rules
  script:
    - docker image inspect jubair2002/api-gateway:api-gateway-$CI_COMMIT_SHORT_SHA
    - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
    - docker push jubair2002/api-gateway:api-gateway-$CI_COMMIT_SHORT_SHA

update-api-gateway-manifest:
  stage: update-manifest
  <<: *api_gateway_rules
  script:
    - git clone https://oauth2:${GITLAB_TOKEN}@gitlab.com/public-project8832250/microservice-manifest-repo.git
    - cd microservice-manifest-repo/k8s-manifests
    - yq eval ".spec.template.spec.containers[0].image = \"jubair2002/api-gateway:api-gateway-$CI_COMMIT_SHORT_SHA\"" -i apiGateway-deploy-svc.yml
    - git commit -am "Update api gateway image"
    - git push origin main

