.api_gateway_rules: &api_gateway_rules
  rules:
    - changes:
        - api-gateway/**/*
      when: always
    - when: never

stages:
  - build
  - push
  - update-manifest

variables:
  SERVICE_NAME: api-gateway
  IMAGES_NAME: jubair2002/api-gateway
  IMAGE_TAG: $CI_COMMIT_SHA

build_api-gateway:
  stage: build
  <<: *api_gateway_rules
  script:
    - echo "Building $SERVICE_NAME Docker image..."
    - docker build -t $IMAGES_NAME:$IMAGE_TAG api-gateway

push_api-gateway:
  stage: push
  <<: *api_gateway_rules
  script:
    - echo "Pushing $SERVICE_NAME Docker image to registry....."
    - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
    - docker push $IMAGES_NAME:$IMAGE_TAG

update-api-gateway-manifest:
  stage: update-manifest
  <<: *api_gateway_rules
  script:
    - echo "Updating manifest"
    - rm -rf microservice-manifest-repo
    - git clone https://oauth2:${GITLAB_TOKEN}@gitlab.com/public-project8832250/microservice-manifest-repo.git  
    - cd microservice-manifest-repo/k8s-manifests
    - yq eval ".spec.template.spec.containers[0].image = \"$IMAGES_NAME:$IMAGE_TAG\"" -i apiGateway-deploy-svc.yml
    - git config user.email "ci@gitlab.com"
    - git config user.name "GitLab CI"
    - git add apiGateway-deploy-svc.yml
    - git commit -m "Update api Gateway image to $IMAGE_TAG"
    - git push origin main

