.frontend_rules: &frontend_rules
  rules:
    - changes:
        - frontend/**/*
      when: always
    - when: never

build_frontend:
  stage: build
  <<: *frontend_rules
  script:
    - docker images "jubair2002/frontend*" -q | xargs -r docker rmi -f
    - docker build --no-cache -t jubair2002/frontend:frontend-$CI_COMMIT_SHORT_SHA frontend

push_frontend:
  stage: push
  <<: *frontend_rules
  script:
    - docker image inspect jubair2002/frontend:frontend-$CI_COMMIT_SHORT_SHA
    - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
    - docker push jubair2002/frontend:frontend-$CI_COMMIT_SHORT_SHA

update-frontend-manifest:
  stage: update-manifest
  <<: *frontend_rules
  script:
    - git clone https://oauth2:${GITLAB_TOKEN}@gitlab.com/public-project8832250/microservice-manifest-repo.git
    - cd microservice-manifest-repo/k8s-manifests
    - yq eval ".spec.template.spec.containers[0].image = \"jubair2002/frontend:frontend-$CI_COMMIT_SHORT_SHA\"" -i frontend-deploy-svc.yml
    - git commit -am "Update frontend image"
    - git push origin main
