.payment_service: &payment_service_rules
  rules:
    - changes:
        - payment-service/**/*
      when: always
    - when: never

build_payment_service:
  stage: build
  <<: *payment_service_rules
  script:
    - docker images "jubair2002/payment-service*" -q | xargs -r docker rmi -f
    - docker build --no-cache -t jubair2002/payment-service:payment-service-$CI_COMMIT_SHORT_SHA payment-service

push_payment_service:
  stage: push
  <<: *payment_service_rules
  script:
    - docker image inspect jubair2002/payment-service:payment-service-$CI_COMMIT_SHORT_SHA
    - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
    - docker push jubair2002/payment-service:payment-service-$CI_COMMIT_SHORT_SHA

update-payment-manifest:
  stage: update-manifest
  <<: *payment_service_rules
  script:
    - git clone https://oauth2:${GITLAB_TOKEN}@gitlab.com/public-project8832250/microservice-manifest-repo.git
    - cd microservice-manifest-repo/k8s-manifests
    - yq eval ".spec.template.spec.containers[0].image = \"jubair2002/payment-service:payment-service-$CI_COMMIT_SHORT_SHA\"" -i payment-deploy-svc.yml
    - git commit -am "Update payment service image"
    - git push origin main

