variables:
  SERVICE_NAME: api-gateway
  IMAGE_NAME: jubair2002/api-gateway
  IMAGE_TAG: $CI_COMMIT_SHA

build_api-gateway:
  stage: build
  script:
    - echo "Building $SERVICE_NAME Docker image..."
    - docker build -t $IMAGE_NAME:$IMAGE_TAG api-gateway

push_api-gateway:
  stage: push
  script:
    - echo "Pushing $SERVICE_NAME Docker image to registry..."
    - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
    - docker push $IMAGE_NAME:$IMAGE_TAG

update_api_gateway_manifest:
  stage: update-manifest
  script:
  - echo "Updating Kubernetes manifest for API Gateway"
  - rm -rf microservice-manifest-repo || true
  - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/public-project8832250/microservice-manifest-repo.git
  - cd microservice-manifest-repo/k8s-manifests
  - sed -i "s#image:.*#image: $IMAGES_NAME:$IMAGE_TAG#" apiGateway-deploy-svc.yml
  - git config user.email "ci@gitlab.com"
  - git config user.name "GitLab CI"
  - git add apiGateway-deploy-svc.yml
  - git commit -m "Update API Gateway image to $IMAGE_TAG"
  - git push origin main